language: bash
sudo: required

notifications:
  - email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y texinfo

script:

after_success:
  - bash build-documentation-pages.sh
